[package]
name = "cloudflare_dns_updater"
version = "1.2.10"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.24", features = ["json"] }
tokio = { version = "1.48", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
dotenv = "0.15"
